# Generated by Django 4.1.5 on 2023-01-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_slug_delete_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostOn',
        ),
    ]
